name: black-format check

on: [pull_request]

jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: jpetrucciani/black-check@21.12b0
        with:
          path: "./scripts"
          black_flags: "--check"
