name: Run C++ formatting

on: [pull_request]

jobs:
  run-formatting:
    name: Run formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      
      - name: Run clang formatting
        run: |
            find ./ -type f -regextype egrep -regex '\.\/(src|include)\/.*\.(cpp|cxx|c|hpp|hxx|h)' |
            xargs clang-format -i

      - name: Commit c++ formatting changes
        uses: Endbug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 'Fix C++ formatting'
